name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dori2005
          template: classic
          base: ""
          filename: metrics.isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dori2005
          template: classic
          base: ""
          filename: metrics.achievements.svg
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
